---
# Source: boutique/charts/orders/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boutique-orders
  labels:
    helm.sh/chart: orders-0.1.0
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: boutique
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
      app.kubernetes.io/instance: boutique
  template:
    metadata:
      annotations:
        restartedAt: "2026-08-12"
      labels:
        app.kubernetes.io/name: orders
        app.kubernetes.io/instance: boutique
    spec:
      serviceAccountName: boutique-orders
      securityContext:
        {}
      containers:
        - name: orders
          envFrom:
            - configMapRef:
                name: boutique-orders
          securityContext:
            {}
          image: "368763425814.dkr.ecr.us-east-1.amazonaws.com/prod/orders:e0603a384948991060a4e6fa5653024dd256bd65"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/metrics
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /api/metrics
              port: http
          resources:
            {}

