---
# Source: boutique/charts/orders/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boutique-orders
  labels:
    helm.sh/chart: orders-0.1.0
    app.kubernetes.io/name: orders
    app.kubernetes.io/instance: boutique
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm

