---
# Source: boutique/charts/order-service/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: boutique-order-service
  labels:
    helm.sh/chart: order-service-0.1.0
    app.kubernetes.io/name: order-service
    app.kubernetes.io/instance: boutique
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  {}

