---
# Source: boutique/charts/order-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boutique-order-service
  labels:
    helm.sh/chart: order-service-0.1.0
    app.kubernetes.io/name: order-service
    app.kubernetes.io/instance: boutique
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service
      app.kubernetes.io/instance: boutique
  template:
    metadata:
      annotations:
        restartedAt: "2026-08-12"
      labels:
        app.kubernetes.io/name: order-service
        app.kubernetes.io/instance: boutique
    spec:
      serviceAccountName: boutique-order-service
      securityContext:
        {}
      containers:
        - name: order-service
          envFrom:
            - configMapRef:
                name: boutique-order-service
          securityContext:
            {}
          image: "368763425814.dkr.ecr.us-east-1.amazonaws.com/prod/order-service:d56628e6be71f021a5d5baa261ddd0d89b31fe97"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {}

