---
# Source: boutique/charts/user-service/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: boutique-user-service
  labels:
    helm.sh/chart: user-service-0.1.0
    app.kubernetes.io/name: user-service
    app.kubernetes.io/instance: boutique
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  {}

