---
# Source: boutique/charts/user-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boutique-user-service
  labels:
    helm.sh/chart: user-service-0.1.0
    app.kubernetes.io/name: user-service
    app.kubernetes.io/instance: boutique
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
      app.kubernetes.io/instance: boutique
  template:
    metadata:
      annotations:
        restartedAt: "2026-08-12"
      labels:
        app.kubernetes.io/name: user-service
        app.kubernetes.io/instance: boutique
    spec:
      serviceAccountName: boutique-user-service
      securityContext:
        {}
      containers:
        - name: user-service
          envFrom:
            - configMapRef:
                name: boutique-user-service
          securityContext:
            {}
          image: "368763425814.dkr.ecr.us-east-1.amazonaws.com/prod/user-service:293a75308cc0c210d3f2313d673866b666762207"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/metrics
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /api/metrics
              port: http
          resources:
            {}

