---
# Source: boutique/charts/auth/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: boutique-auth
  labels:
    helm.sh/chart: auth-0.1.0
    app.kubernetes.io/name: auth
    app.kubernetes.io/instance: boutique
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm

