---
# Source: boutique/charts/product-service/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: boutique-product-service
  labels:
    helm.sh/chart: product-service-0.1.0
    app.kubernetes.io/name: product-service
    app.kubernetes.io/instance: boutique
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  DATABASE_URL: postgresql://bplOBle:BQjzZKgBCeNyv4Q%23@boutique-db-prod.ca1smsmwkm6y.us-east-1.rds.amazonaws.com:5432/boutique?sslmode=no-verify
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  PORT: "80"

