---
# Source: boutique/charts/product-service/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: boutique-product-service
  labels:
    helm.sh/chart: product-service-0.1.0
    app.kubernetes.io/name: product-service
    app.kubernetes.io/instance: boutique
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  {}

