---
# Source: boutique/charts/gateway/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: boutique-gateway
  labels:
    helm.sh/chart: gateway-0.1.0
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: boutique
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  AUTH_SERVICE_URL: http://auth:80
  GATEWAY_PORT: "80"
  ORDER_SERVICE_URL: http://order-service:80
  ORDERS_SERVICE_URL: http://orders:80
  PORT: "80"
  PRODUCTS_SERVICE_URL: http://product-service:80
  USERS_SERVICE_URL: http://user-service:80

